---

services:
  knot:
    #image: docker.io/tngl/knot:v1.10.0-alpha
    image: andrewzah/knot:1.11.0-alpha
    ports:
      - "5555:5555"
    env_file:
      - ./.env
    volumes:
      - "./data/git/:/data/git/"
